repos:
- repo: local
  hooks:
    - id: pylint
      name: pylint
      #entry: python3 -m pylint --recursive true .
      entry: python3 -m pylint --recursive true .
      language: system
      types: [python]
      #exclude: src/build/
      always_run: true
      pass_filenames: false