name: Lint

on:
  push:
    tags:
      - '**'
    branches:
<<<<<<< HEAD
=======
      - main
>>>>>>> origin/main
      - initial-implementation

jobs:
#  lint:
#    name: "Lint"
#    runs-on: [self-hosted, general-linter]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Lint
#        shell: bash
#        run: |
#          make lint

  release:
    permissions:
      contents: write
    name: "Release"
    runs-on: [self-hosted, releaser]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        id: build
        shell: bash
        run: |
          pwd
          ls -lRa;
          make build;
          cd /home/runner;
          ls -lRa
      - run: |
          echo "DOCKER_USERNAME=ideamixes" >> "$GITHUB_ENV"
          echo "DOCKER_PASSWORD=${GITHUB_TOKEN}" >> "$GITHUB_ENV"
      - run: npx semantic-release-plus --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx semantic-release-plus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}

